services:
  natrix2_cont1:
    image: dbeisser/natrix2:latest # Docker image
    # build: . Create your own Docker image
    restart: on-failure # Restarts the container if an error occurs
    environment:
      PROJECT_NAME: ${PROJECT_NAME} # Set the environment variable
    volumes:
      - /srv/docker/natrix2_smps1/input:/app/input # Mount: directory for input data
      - /srv/docker/natrix2_smps1/output:/app/output # Mount: directory for results
      - /srv/docker/natrix2_smps1/database:/app/database # Mount: directory for the database
      - /srv/docker/natrix2_smps1/demultiplexed:/app/demultiplexed # Mount: directory for demultiplexed data


# You can use multiple containers (natrix2_cont1, natrix2_cont2).
# It is important that you use different project names and folders.
# You replace ${PROJECT_NAME} with a fixed name. For all containers!
# Then start with the command: sudo docker compose up


#  natrix2_cont2:
#    image: dbeisser/natrix2:latest # Docker image
#    # build: . Create your own Docker image
#    restart: on-failure # Restarts the container if an error occurs
#    environment:
#      PROJECT_NAME: project_name # Set the environment variable
#    volumes:
#      - /srv/docker/natrix2_smps2/input:/app/input # Mount: directory for input data
#      - /srv/docker/natrix2_smps2/output:/app/output # Mount: directory for results
#      - /srv/docker/natrix2_smps2/database:/app/database # Mount: directory for the database
#      - /srv/docker/natrix2_smps2/demultiplexed:/app/demultiplexed # Mount: directory for demultiplexed data