services:
  natrix2_cont1: # CONTAINER_1
    image: dbeisser/natrix2:latest # Docker image
    # build: . Create your own Docker image
    # Restarts the container if an error occurs
    restart: on-failure
    environment:
      # Must match config file in input folder
      PROJECT_NAME: ${PROJECT_NAME}
    volumes:
      # Mount: directory for input data
      - /srv/docker/natrix2_cont_1/input:/app/input
      # Mount: directory for results
      - /srv/docker/natrix2_cont_1/output:/app/output
      # Mount: directory for the database
      - /srv/docker/natrix2_cont_1/database:/app/database
      # Mount: directory for demultiplexed data
      - /srv/docker/natrix2_cont_1/demultiplexed:/app/demultiplexed

# Important: Running Multiple Containers
# When running multiple containers (e.g., natrix2_cont1 and natrix2_cont2),
# use a unique project name and a separate directory for each container.
# Replace ${PROJECT_NAME} with a fixed name that matches each config file.
# Start all configured containers with: sudo docker compose up

#  natrix2_cont2: # CONTAINER_2
#    image: dbeisser/natrix2:latest # Docker image
#    # build: . Create your own Docker image
#    # Restarts the container if an error occurs
#    restart: on-failure
#    environment:
#      # Must match config file in input folder
#      PROJECT_NAME: project_name
#    volumes:
#      # Mount: directory for input data
#      - /srv/docker/natrix2_cont_2/input:/app/input
#      # Mount: directory for results
#      - /srv/docker/natrix2_cont_2/output:/app/output
#      # Mount: directory for the database
#      - /srv/docker/natrix2_cont_2/database:/app/database
#      # Mount: directory for demultiplexed data
#      - /srv/docker/natrix2_cont_2/demultiplexed:/app/demultiplexed
